import React from 'react';

const steps = [
  {
    number: '01',
    title: 'Take the Comprehensive Quiz',
    description: 'Invest a few minutes in our interactive quiz to tell us about your academics, interests, and personality. This forms the foundation of your unique profile.',
    imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=800&auto=format&fit=crop'
  },
  {
    number: '02',
    title: 'Receive Your AI Profile',
    description: 'Instantly get your personalized dashboard. See your skill fingerprint, top career matches, and initial recommendations generated by our AI.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop'
  },
  {
    number: '03',
    title: 'Explore Career Paths',
    description: 'Dive deep into recommended careers. Understand roles, market demand in India, required skills, and see what a "day in the life" looks like.',
    imageUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=800&auto=format&fit=crop'
  },
  {
    number: '04',
    title: 'Generate Your Learning Roadmap',
    description: 'Select a career and let our AI build a custom, step-by-step plan to bridge your skill gaps, complete with courses, projects, and resources.',
    imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=800&auto=format&fit=crop'
  },
];

const HowItWorks: React.FC = () => {
  return (
    <section id="how-it-works" className="py-20 sm:py-32 bg-gray-900/20">
      <div className="container mx-auto px-6">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-extrabold tracking-tight">
            Your Journey to Clarity in <span className="gradient-text">4 Simple Steps</span>
          </h2>
          <p className="mt-4 text-lg text-gray-400">
            We've streamlined the complex process of career planning into a clear, actionable journey.
          </p>
        </div>
        <div className="relative">
          <div className="hidden lg:block absolute left-1/2 -translate-x-1/2 top-10 bottom-10 w-px bg-gray-700"></div>
          {steps.map((step, index) => {
            const isEven = index % 2 === 0;

            const textContent = (
              <div className={`p-6 rounded-2xl border border-gray-800 bg-[#020410]`}>
                <h3 className="text-2xl font-bold text-sky-400 mb-2">{step.number}. {step.title}</h3>
                <p className="text-gray-400">{step.description}</p>
              </div>
            );

            const imageContent = (
              <div className="mt-6 lg:mt-0">
                <img src={step.imageUrl} alt={step.title} className="rounded-2xl shadow-xl shadow-black/20 w-full object-cover aspect-video" />
              </div>
            );

            return (
              <div key={index} className="lg:grid lg:grid-cols-[1fr_auto_1fr] lg:gap-x-12 items-center mb-12">
                {isEven ? (
                  <>
                    <div className="lg:text-right">{textContent}</div>
                    <div className="hidden lg:flex justify-center">
                      <div className="w-4 h-4 rounded-full bg-sky-500 shadow-lg shadow-sky-500/50"></div>
                    </div>
                    <div>{imageContent}</div>
                  </>
                ) : (
                  <>
                    <div className="hidden lg:block">{imageContent}</div>
                    <div className="hidden lg:flex justify-center">
                      <div className="w-4 h-4 rounded-full bg-sky-500 shadow-lg shadow-sky-500/50"></div>
                    </div>
                    <div className="lg:text-left">{textContent}</div>
                    {/* On mobile, show image below text */}
                    <div className="lg:hidden">{imageContent}</div>
                  </>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default HowItWorks;